import { StyleStatus } from "@/app/interface/ImageData";

export const styles: StyleStatus[] = [
  { value: "Realism", label: "现实主义" },
  { value: "Impressionism", label: "印象派" },
  { value: "Expressionism", label: "表现主义" },
  { value: "Abstract Expressionism", label: "抽象表现主义" },
  { value: "Analytical Cubism", label: "分析立体主义" },
  { value: "Post-Impressionism", label: "后印象派" },
  { value: "Fauvism", label: "色彩派" },
  { value: "Cubism", label: "立体主义" },
  { value: "Surrealism", label: "超现实主义" },
  { value: "Les Fauves", label: "野兽派" },
  { value: "Neo-Expressionism", label: "新表现主义" },
  { value: "Modernism", label: "摩登主义" },
  { value: "Sketching", label: "素描" },
  { value: "European Romanticism", label: "欧洲浪漫主义" },
  { value: "Ink Wash Painting", label: "水墨画" },
  { value: "Oil Painting", label: "油画" },
  { value: "Watercolor Painting", label: "水彩画" },
  { value: "Pointillism", label: "点彩画" },
  { value: "Tonalism", label: "朦胧派" },
  { value: "Minimalism", label: "极简主义" },
  { value: "Street Art", label: "街头艺术" },
  { value: "Environmental Art", label: "环境艺术" },
  { value: "Digital Art", label: "数字艺术" },
  { value: "Japanese Anime", label: "日本动漫" },
  { value: "Photography", label: "摄影师" },
  { value: "Movies", label: "电影" },
  { value: "Cyberpunk", label: "赛博朋克" },
];
