import { StyleStatus } from "@/lib/interface/ImageData";

export const styleTags: StyleStatus[] = [
  { value: "Realism", label: "现实主义" },
  { value: "Impressionism", label: "印象派" },
  { value: "Expressionism", label: "表现主义" },
  { value: "Analytical Cubism", label: "分析立体主义" },
  { value: "Post-Impressionism", label: "后印象派" },
  { value: "Fauvism", label: "色彩派" },
  { value: "Cubism", label: "立体主义" },
  { value: "Surrealism", label: "超现实主义" },
  { value: "Les Fauves", label: "野兽派" },
  { value: "Neo-Expressionism", label: "新表现主义" },
  { value: "Modernism", label: "摩登主义" },
  { value: "Sketching", label: "素描" },
  { value: "European Romanticism", label: "欧洲浪漫主义" },
  { value: "Ink Wash Painting", label: "水墨画" },
  { value: "Oil Painting", label: "油画" },
  { value: "Watercolor Painting", label: "水彩画" },
  { value: "Pointillism", label: "点彩画" },
  { value: "Tonalism", label: "朦胧派" },
  { value: "Minimalism", label: "极简主义" },
  { value: "Street Art", label: "街头艺术" },
  { value: "Environmental Art", label: "环境艺术" },
  { value: "Digital Art", label: "数字艺术" },
  { value: "Japanese Anime", label: "日本动漫" },
  { value: "Photography", label: "摄影师" },
  { value: "Movies", label: "电影" },
  { value: "Cyberpunk", label: "赛博朋克" },
  { value: "Classicism", label: "古典主义" },
  { value: "Romanticism", label: "浪漫主义" },
  { value: "Baroque", label: "巴洛克" },
  { value: "Renaissance", label: "文艺复兴" },
  { value: "Symbolism", label: "象征主义" },
  { value: "Pre-Raphaelite Brotherhood", label: "前拉斐尔派" },
  { value: "Dadaism", label: "达达主义" },
  { value: "Cubofuturism", label: "立体未来主义" },
  { value: "Suprematism", label: "至上主义" },
  { value: "Constructivism", label: "构成主义" },
  { value: "Abstract Art", label: "抽象艺术" },
  { value: "Op Art", label: "视觉艺术" },
  { value: "Kinetic Art", label: "动态艺术" },
  { value: "Conceptual Art", label: "概念艺术" },
  { value: "Land Art", label: "地景艺术" },
  { value: "Performance Art", label: "行为艺术" },
  { value: "Video Art", label: "视频艺术" },
  { value: "Installation Art", label: "装置艺术" },
  { value: "Sound Art", label: "声音艺术" },
  { value: "Body Art", label: "身体艺术" },
  { value: "Holography", label: "全息艺术" },
  { value: "Futurism", label: "未来主义" },
  { value: "Sonic Art", label: "声波艺术" },
  { value: "Avant-Garde", label: "先锋派" },
  { value: "Abstract Expressionism", label: "抽象表现主义" },
  { value: "Digital Painting", label: "数字绘画" },
  { value: "Street Photography", label: "街头摄影" },
  { value: "Graffiti Art", label: "涂鸦艺术" },
  { value: "Trompe-l'oeil", label: "目眩术" },
  { value: "Art Deco", label: "装饰艺术" },
  { value: "Gothic", label: "哥特式" },
  { value: "Surreal Pop", label: "超现实流行" },
  { value: "Naïve Art", label: "天真艺术" },
  { value: "Art Nouveau", label: "新艺术" },
  { value: "Romantic Realism", label: "浪漫现实主义" },
  { value: "Magical Realism", label: "魔幻现实主义" },
  { value: "Hyperrealism", label: "超写实主义" },
  { value: "Neo-Classicism", label: "新古典主义" },
  { value: "Transcendental Painting", label: "超验主义绘画" },
  { value: "Documentary Photography", label: "纪实摄影" },
  { value: "Portrait Photography", label: "人像摄影" },
  { value: "Fashion Photography", label: "时尚摄影" },
  { value: "Landscape Photography", label: "风景摄影" },
  { value: "Macro Photography", label: "微距摄影" },
  { value: "Aerial Photography", label: "航拍摄影" },
  { value: "Underwater Photography", label: "水下摄影" },
  { value: "Night Photography", label: "夜景摄影" },
  { value: "Wildlife Photography", label: "野生动物摄影" },
];

export const randomPrompts = [
  "serene landscape with rolling hills, bathed in the warm glow of the setting sun, captured in the style of impressionist brushstrokes, with a touch of ethereal mist.",
  "solitary figure standing on a cliff edge, silhouetted against the fiery hues of a breathtaking sunset, rendered in the style of dramatic chiaroscuro.",
  "bustling city street, alive with neon lights and bustling crowds, captured in the gritty realism of urban photography, with hints of cinematic noir.",
  "tranquil forest scene, with sunlight filtering through the canopy of ancient trees, evoking a sense of tranquility and reverence, reminiscent of classical landscape paintings.",
  "futuristic metropolis, towering skyscrapers reaching towards the sky, bathed in the neon glow of holographic advertisements, in the style of cyberpunk digital art.",
  "cozy cafe scene, with steaming cups of coffee and the murmur of conversation, rendered in the warm tones and soft focus of vintage photography.",
  "windswept coastline, with waves crashing against rugged cliffs, captured in the dynamic brushstrokes and vibrant colors of impressionist seascape paintings.",
  "mystical forest glade, illuminated by shafts of golden sunlight, inhabited by mystical creatures and ancient spirits, in the style of fantasy illustration.",
  "retro-futuristic cityscape, with flying cars zipping between towering skyscrapers, rendered in the sleek lines and bold colors of 1980s sci-fi art.",
  "dreamlike underwater world, with colorful coral reefs and exotic sea creatures, bathed in the soft glow of bioluminescent light, reminiscent of surrealist paintings.",
  "Enchanted forest bathed in the golden light of dawn, with dewdrops glistening on emerald leaves, captured in the style of fairytale illustrations.",
  "Majestic mountains, towering against the azure sky, with wisps of clouds dancing around their peaks, rendered in the grandeur of epic landscape paintings.",
  "Whimsical carnival scene, with carousel horses frozen in mid-gallop and cotton candy clouds floating overhead, in the style of surrealistic dreamscapes.",
  "Ancient ruins, shrouded in the mists of time, with crumbling columns and ivy-clad walls, evoking the echoes of lost civilizations, captured in the haunting beauty of ruins photography.",
  "Ethereal underwater kingdom, with shimmering mermaids and iridescent coral reefs, bathed in the soft glow of bioluminescent creatures, reminiscent of mythical tales.",
  "Industrial wasteland, with rusted machinery and crumbling factories, surrounded by toxic fumes and desolation, captured in the stark realism of urban decay photography.",
  "Magical garden, with cascading waterfalls and blooming flowers of every hue, inhabited by playful fairies and woodland creatures, in the style of whimsical fantasy art.",
  "Apocalyptic cityscape, with skyscrapers crumbling and streets littered with debris, as nature reclaims its dominion, captured in the haunting beauty of urban decay.",
  "Charming countryside scene, with quaint cottages nestled among rolling hills and fields of wildflowers, bathed in the golden light of sunset, in the style of pastoral landscapes.",
  "Otherworldly moonscape, with towering alien spires and glowing crystal formations, under the watchful gaze of distant planets, in the style of cosmic fantasy art.",
];
